version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      minor-update:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/tools/*"
    schedule:
      interval: "monthly"
    groups:
      minor-update:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
