# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: aws_finder

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/aws_finder
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin

gomod:
  proxy: true

checksum:
  name_template: sha256sums.txt
  algorithm: sha256
  split: false

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - binary

release:
  target_commitish: '{{ .Commit }}'
