name: Scorecard analysis workflow
on:
  push:
    # Only the default branch is supported.
    branches:
      - master
  schedule:
    # Weekly on Saturdays.
    - cron:  '30 1 * * 6'

concurrency: # Avoid needlessly running the same workflow multiple times
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read # (Probably) required to perform the analysis
      actions: read # (Probably) required to perform the analysis
      checks: read # (Probably) required to perform the analysis
      issues: read # (Probably) required to perform the analysis
      pull-requests: read # (Probably) required to perform the analysis
      statuses: read # (Probably) required to perform the analysis
      security-events: write # Needed to upload the results to code-scanning dashboard.

    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: false

      # Upload the results to GitHub's code scanning dashboard (optional).
      # Commenting out will disable upload of results to your repo's Code Scanning dashboard
      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4.35.2
        with:
          sarif_file: results.sarif
